# Generated by Django 2.1.9 on 2020-08-04 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobID', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Company_Category')),
            ],
            options={
                'ordering': ['JobID'],
            },
        ),
    ]
